name: Build ARM Native Image

on:
  push:
    branches:
      - master
    paths:
      - 'pom.xml'

jobs:
  build-arm:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if version changed
        id: version_check
        run: |
          CURRENT_VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)

          # Fetch minimal history to get previous pom.xml
          git fetch origin master --depth=2
          git show HEAD^:pom.xml > pom_old.xml || true
          PREVIOUS_VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom_old.xml || echo "")

          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $PREVIOUS_VERSION"

          # Always set version for later steps
          echo "version=$CURRENT_VERSION" >> $GITHUB_ENV

          if [ "$CURRENT_VERSION" = "$PREVIOUS_VERSION" ]; then
            echo "changed=false" >> $GITHUB_ENV
            echo "No version change detected — skipping build."
          else
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Create GitHub release (draft if not exists)
        if: env.changed == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          name: SnapZap ${{ env.version }}
          draft: true
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up GraalVM JDK
        if: env.changed == 'true'
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 25.ea.28-graal
          sdk use java 25.ea.28-graal
          sdk install maven 4.0.0-rc-4
          sdk use maven 4.0.0-rc-4
          java -version
          mvn -version

      - name: Clean Maven
        if: env.changed == 'true'
        run: mvn clean

      - name: Prepare Intel Build Directory
        if: env.changed == 'true'
        run: mkdir -p target/ARM

      - name: Build ARM native image
        if: env.changed == 'true'
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          mvn -PnativeARM -DskipTests native:compile
          cd target/ARM
          mv SnapZap snapzap
          tar -czvf snapzap-${{ env.version }}-macos-arm64.tar.gz snapzap
          zip -j snapzap-${{ env.version }}-macos-arm64.zip snapzap

      - name: Upload ARM artifacts to release
        if: env.changed == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          files: |
            snapzap-${{ env.version }}-macos-arm64.tar.gz
            snapzap-${{ env.version }}-macos-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
