name: Test and Check The Environment
on:
  workflow_dispatch:

jobs:
  check-environment:
    runs-on: macos-13
    steps:
      - name: Cache SDKMAN
        uses: actions/cache@v4
        with:
          path: ~/.sdkman
          key: sdkman-${{ runner.os }}-${{ runner.arch }}-graal25ea28-maven4rc4

      - name: Set up GraalVM JDK
        run: |
          if [ ! -f "$HOME/.sdkman/bin/sdkman-init.sh" ]; then
            curl -s "https://get.sdkman.io" | bash
          fi

          source "$HOME/.sdkman/bin/sdkman-init.sh"

          # Install only if not already cached
          if [ ! -d "$HOME/.sdkman/candidates/java/25.ea.28-graal" ]; then
            sdk install java 25.ea.28-graal
          fi

          if [ ! -d "$HOME/.sdkman/candidates/maven/4.0.0-rc-4" ]; then
            sdk install maven 4.0.0-rc-4
          fi

          sdk use java 25.ea.28-graal
          sdk use maven 4.0.0-rc-4
          java -version
          mvn -version

      - name: Get Information
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          java --version
          mvn --version
