name: Update Homebrew Tap Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to update"
        required: true

jobs:
  update-formula:
    runs-on: macos-latest

    steps:
      - name: Check out tap repository
        run: |
          git clone https://x-access-token:${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/EasyG0ing1/homebrew-tools.git
          cd homebrew-tools
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download ARM artifact
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "Version is $VERSION"
          curl -sSL -f -o arm.tar.gz \
            "https://github.com/EasyG0ing1/SnapZap/releases/download/${VERSION}/snapzap-${VERSION}-macos-arm64.tar.gz"

      - name: Download Intel artifact
        run: |
          VERSION="${{ github.event.inputs.version }}"
          curl -sSL -f -o intel.tar.gz \
            "https://github.com/EasyG0ing1/SnapZap/releases/download/${VERSION}/snapzap-${VERSION}-macos-x64.tar.gz"

      - name: Verify artifacts exist
        run: |
          if [ ! -s arm.tar.gz ]; then
            echo "❌ ARM artifact is missing or empty"
            exit 1
          fi
          if [ ! -s intel.tar.gz ]; then
            echo "❌ Intel artifact is missing or empty"
            exit 1
          fi
          echo "✅ Both artifacts found"

      - name: Calculate SHA256 checksums
        run: |
          ARM_SHA=$(shasum -a 256 arm.tar.gz | awk '{print $1}')
          INTEL_SHA=$(shasum -a 256 intel.tar.gz | awk '{print $1}')
          echo "ARM_SHA=$ARM_SHA" >> $GITHUB_ENV
          echo "INTEL_SHA=$INTEL_SHA" >> $GITHUB_ENV

      - name: Update formula file
        working-directory: homebrew-tools
        run: |
          VERSION="${{ github.event.inputs.version }}"
          FORMULA_FILE=Formula/snapzap.rb

          # Update version
          sed -i '' "s/version \".*\"/version \"${VERSION}\"/" $FORMULA_FILE

          # Update ARM URL & SHA
          sed -i '' "s|url \".*-macos-arm64.tar.gz\"|url \"https://github.com/EasyG0ing1/SnapZap/releases/download/${VERSION}/snapzap-${VERSION}-macos-arm64.tar.gz\"|" $FORMULA_FILE
          sed -i '' "s|sha256 \".*\" # arm64|sha256 \"${ARM_SHA}\" # arm64|" $FORMULA_FILE

          # Update Intel URL & SHA
          sed -i '' "s|url \".*-macos-x64.tar.gz\"|url \"https://github.com/EasyG0ing1/SnapZap/releases/download/${VERSION}/snapzap-${VERSION}-macos-x64.tar.gz\"|" $FORMULA_FILE
          sed -i '' "s|sha256 \".*\" # x64|sha256 \"${INTEL_SHA}\" # x64|" $FORMULA_FILE

      - name: Commit and push changes
        working-directory: homebrew-tools
        run: |
          if ! git diff --quiet; then
            git add Formula/snapzap.rb
            git commit -m "Bump snapzap to ${{ github.event.inputs.version }}"
            git push
          else
            echo "No changes to commit."
          fi
